sudo: required
dist: trusty
language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker pull kengz/aiva
  - docker run -m 4G -it -d -p 4041:4038 -p 7476:7475 -p 6466:6465 --name aiva-development -v `pwd`:/opt/aiva kengz/aiva /bin/bash -c 'NPM_RUN=\"development\" && cd /opt/aiva && npm install'
  - docker ps -a
install:
  - sudo npm install
script:
  - sudo npm test
after_script:
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"