sudo: required
dist: trusty
language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker pull kengz/aiva
  - docker run -m 4G -it -d -p 4041:4038 -p 7476:7475 -p 6466:6465 --name aiva-development -v `pwd`:/opt/aiva kengz/aiva /bin/bash -c 'NPM_RUN=\"development\" && cd /opt/aiva && npm install'
  - docker ps -a
install:
  - npm install bluebird
  - npm install co
  - npm install concept-net
  - npm install coveralls
  - npm install date.js
  - npm install download
  - npm install express
  - npm install geocoder
  - npm install google
  - npm install googleapis
  - npm install hubot
  - npm install hubot-diagnostics
  - npm install hubot-fb
  - npm install hubot-slack
  - npm install hubot-telegram
  - npm install indico.io
  - npm install log
  - npm install lomath
  - npm install neo4jkb
  - npm install node-env-file
  - npm install node-wit
  - npm install path-exists
  - npm install portfinder
  - npm install randombytes
  - npm install reqscraper
  - npm install require-dir
  - npm install requireg
  - npm install socket.io
  - npm install socket.io-client
  - npm install untildify
  - npm install watson-developer-cloud
script:
  - npm test
after_script:
  "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"